seed: 42
model_dir: ../../models/tfm-tts
resume_checkpoint: true

train:
  fp16: true
  batch_size: 32
  num_epochs: 1000
  save_interval: 100

data:
  data_dir: ./DATA

model:
  n_mel: 80

  embedding:
    n_phoneme: 38
    n_accent: 19

  encoder:
    channels: 256
    n_heads: 2
    n_layers: 4
    dropout: 0.1

  variance_adopter:
    channels: 256
    dropout: 0.5

  decoder:
    channels: 256
    n_heads: 2
    n_layers: 4
    kernel_size: 7
    dropout: 0.1

optimizer:
  lr: 1.0
  betas: [0.9, 0.98]
